config/routes.rb
Obligatorio::Application.routes.draw do
  get "welcome/index" 
  resources :tweets

  resources :users

  root 'welcome#index'

  get 'welcome/buscar' => 'welcome#buscar', as: :buscarusuario

  get 'welcome/listar/:id' => 'welcome#listar', as: :listarusuario

  

  match ':controller(/:action(/:id))(.:format)' , via: [:post, :get]
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	validates :contenido, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets
	validates_uniqueness_of :usuario
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'El Tweet ha sido creado con exito.' }
        format.json { render action: 'show', status: :created, location: @tweet }
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params_edit)
        format.html { redirect_to @tweet, notice: 'El Tweet ha sido modificado con exito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :contenido)
    end

    def tweet_params_edit
      params.require(:tweet).permit(:contenido)
    end

    def t_params
      @user = User.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json

def buscar

end

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end




  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'El usuario ha sido creado con exito.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'El usuario ha sido modificado con exito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nombre, :email, :usuario, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def buscar
  end

  def listar
  	@u = params[:usuario]
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obligatorio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_field :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_tweets.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_field :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Editando..</h1>

  <%= render partial: "/tweets/tweets" %>

<%= link_to 'Atras', users_path %>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Listado de tweets</h1>

<table>
  <thead>
    <tr>
      <th>Contenido</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>      
        <tr>
          <td><%= tweet.id %></td>
          <td><%= tweet.user_id %></td>
          <td><%= tweet.contenido %></td>
          <td><%= link_to 'Editar', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Borrar', tweet, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Pagina Principal', welcome_index_path %>

 

app/views/tweets/new.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Nuevo tweet</h1>

<%= render :partial => '/tweets/tweets' %>

<%= link_to 'Atras', users_path %>

app/views/tweets/show.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
 <%= @user = User.find(@tweet.user_id).usuario %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @tweet.contenido %>
</p>

<%= link_to 'Editar', edit_tweet_path(@tweet) %> |
<%= link_to 'Atras', users_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form2.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/buscar.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Buscar Usuario</h1>


<%= link_to 'Atras', users_path %>

app/views/users/edit.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Editando..</h1>

<%= render 'form' %>

<%= link_to 'Atras', users_path %>

app/views/users/index.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Listado de Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Usuario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        
        <td><%= user.nombre %></td>
        <td><%= user.email %></td>
        <td><%= user.usuario %></td>
        <td><%= link_to 'Twittear', new_tweet_path %></td>
        <td><%= link_to 'Ver Tweets', user_path(user.id) %></td>
        <td><%= link_to '[X]', user, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Pagina Principal', welcome_index_path %>

app/views/users/new.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Nuevo Usuario</h1>

<%= render 'form' %>

<%= link_to 'Atras', users_path %>

app/views/users/show.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<p id="notice"><%= notice %></p>

<p><strong>USUARIO: <%= @user.usuario %></strong></p>
<table>
  <thead>
    <tr>
      <th>Numero del Tweet</th>
      <th>Contenido del Tweet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tweets.each do |tweet| %>
      
      <tr>
        <td><%= tweet.id %></td>
        <td><%= tweet.contenido %></td>
        <td><%= link_to 'Editar', edit_tweet_path(tweet) %></td>
        <td><%= link_to '[X]', tweet, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Editar Usuario', edit_user_path(@user) %> |
<%= link_to 'Atras', users_path %>

app/views/welcome/buscar.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Buscar Usuario</h1>

<p>Ingresar Usuario</p>
      
    <form action = "/welcome/listar" >
	   <td><input type="text" name="usuario"></td>
       <td><input type="submit" value="Buscar"></td>
    </form>

<%= link_to 'Atras', welcome_index_path %>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Bienvenidos a Tweeting</h1>
<p>Por: Alvaro Rameau - Rafael Martinez</p>
<%= link_to 'Crear Usuario', new_user_path %>
<%= link_to 'Listado de Usuarios', users_path %>
<%= link_to 'Buscar Usuarios', :buscarusuario %>

app/views/welcome/listar.html.erb
<%= stylesheet_link_tag "estilo.css" %>
<h1>Datos del Usuario</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Nombre</th>
      <th>Email</th>
      <th>Cantidad de Tweets</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
    <% if user.usuario == @u %>
	   <td><%= user.usuario %></td>
	   <td><%= user.nombre %></td>
	   <td><%= user.email %></td>
	   <td><%= user.tweets.count %></td>
	<% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Buscar Usuario', :buscarusuario %>
<%= link_to 'Pagina Principal', welcome_index_path %>